#+SETUPFILE: ../../org-templates/level-1.org
#+TITLE: Arachneion-Pallashass
#+STARTUP: showall

** Personae
-  Menschen und Tiere
-  [[file:asklepios.org][Asklepios]]: Legendärer Heiler und Teilnehmer der
   Argonautenfahrt.
-  [[file:idmon.org][Idmon]]: Legendärer Seher. Argonaut und Vater der Arachne.
-  [[file:iason.org][Iason]]: Sohn des Aison. Anführer der Argonauten.
-  [[file:arachne.org][Arachne]]: Tochter des Idmon.
-  [[file:colydon.org][Colydon]]: Ziege der Arachne.
-  Götter
-  [[file:zeus.org][Zeus]]: Göttervater und oberster Gott.
-  [[file:hera.org][Hera]]: Seine eifersüchtige Gattin.
-  [[file:hades.org][Hades]]: Herrscher über das Totenreich.
-  [[file:poseidon.org][Poseidon]]: Gott des Meeres.
-  [[file:athene.org][Athene]]: Göttin der Weisheit, der Kunst und des
   Handwerks.
-  Sonstige Begriffe und Fabelwesen
-  [[file:kroniden.org][Kroniden]]: Kinder des Kronos.

   -  [[file:zeus.org][Zeus]]
   -  [[file:hades.org][Hades]]
   -  [[file:poseidon.org][Poseidon]]
   -  [[file:hera.org][Hera]]
   -  [[file:hestia.org][Hestia]]
   -  [[file:demeter.org][Demeter]]

-  [[file:moiren.org][Moiren]]: Schicksalsgöttinnen.

   -  [[file:klotho.org][Klotho]]
   -  [[file:lachesis.org][Lachesis]]
   -  [[file:atropos.org][Atropos]]

-  [[file:aisonide.org][Aisonide]]: Kind des Aison (Iason).
-  Weitere [[file:goetter.org][Götter]] und [[file:fabelwesen.org][Fabelwesen]].

** Zusammenfassung
/Übersicht der einzelnen Gesänge: [[file:arachneion-pallashass-gesaengekatalog.org][Gesängekatalog]]/

In Bithynien wird der Heiler Asklepios vom sterbenden Idmon gebeten,
sich seiner Tochter Arachne anzunehmen. Asklepios beschließt, sie nach
Hypaipa zu führen und unter die Fittiche einer alten Bekannten zu geben.

Bevor er die Stadt Kolophon erreicht, die Heimat der Arachne, stößt er
auf den Hades. Hades eröffnet ihm, dass der Frevel des Asklepios nicht
unbemerkt geblieben ist und er gekommen ist, den Asklepios mit sich in
den Hades zu nehmen. Asklepios bittet den Hades darum, wenigstens noch
die Arachne nach Hypaipa führen zu dürfen. Danach will er sich sofort
dem Hades anschließen und ins Totenreich folgen. Als Asklepios gemeinsam
mit der Arachne und dem Jungen Padmilos die Stadt verlässt, kommt es zum
Angriff der Persischen Flotte. Der Angriff wird von Poseidon
niedergeschlagen, um die Perser zu vernichten entfesselt er jedoch den
Ketos, ein schreckliches Meeresungeheuer, welches die Stadt Kolophon
zerstört.

In Myrina treffen sie erneut auf den Hades. Asklepios tötet ihn mit der
Klinge Hadesbrand. Hades schickt daraufhin den Zerberus aus, um sich an
Asklepios zu rächen. Der Zerberus zerreißt den Asklepios, woraufhin sich
dieser im Totenreich wiederfindet.

Im Totenreich erwachen einige tote Argonauten und erinnern sich an ihr
früheres Leben. Ihr Anführer Iason zettelt einen Aufstand an und die
Toten stürmen gegen die Festung des Hades.

Auf dem Olymp ruft Hera Asklepios und den Iason zu sich und beauftragt
sie, Hilfe für den sterbenden Zeus zu beschaffen. Asklepios erinnert
sich an eine alte Bekannte. Gemeinsam machen sie sich auf den Weg zur
Insel Samothrake.

Auf Samothrake eröffnet die Hexe Hippolaya dem Asklepios, dass Zeus
vergiftet wurde und nur Moirenblut in der Lage ist, den Göttervater zu
retten. Asklepios und die anderen machen sich auf den Weg zur Insel der
Moiren.

Auf der Insel der Moiren verschaffen sie sich mit Hilfe der Hexe
Hippolaya gewaltsam das Blut der Moiren. Die Moire Atropos bleibt dabei
nur verstümmelt zurück. Als sie gerade abreisen wollen, stellt sich die
Hexe Hippolaya ihnen in den Weg und fordert das Blut des Zeus. Im
Gegenzug mischt sie das Gegengift zusammen.

Auf dem Rückweg erscheinen Hera und Athene an Deck der Argo und fordern
das Gegenmittel für sich ein. Das Monstrum Agdistis erscheint an Deck
und greift an. Agdistis kann zurückgeworfen werden, reißt jedoch die
Ziege Colydon mit sich in die Tiefe.

In Hypaipa erscheint der Hades und verlangt den Asklepios. Asklepios
übergibt die Arachne ihrer neuen Lehrmeisterin Orke und will zum Hades
zurückkehren. Die Hybris der Arachne ruft die Athene auf den Plan und
sie rufen einen Wettbewerb aus. In diesem Wettstreit soll ermittelt
werden, wer die größte Weberin ist. Arachne kann den Wettstreit mehr
oder weniger für sich entscheiden, woraufhin Athene sie in eine Spinne
verwandelt. Die Hexe Hippolaya erscheint unerkannt und wirft eine Phiole
in den Verwandlungsstrahl der Athene. Die Arachne verwandelt sich
daraufhin in eine gewaltige Spinnenbestie und verschanzt sich im Tempel
der Athene. Die angreifenden Wachen werden von der Spinnenbestie
zermalmt und sie flüchtet ins Innere der Stadt. Doch statt weiterhin für
Tod und Vernichtung zu sorgen, beginnt sie, die Häuser des
Handwerkerviertels in wunderbare Bildnisse einzuspinnen. Der Anblick
schlägt die Bewohner der Stadt dermaßen in ihren Bann, dass nicht wenige
zu verdursten drohen. Der mittlerweile geheilte Zeus erscheint in der
Stadt, um die Spinnenbestie zu zerschmettern. Der Anblick der Bildnisse
nimmt jedoch selbst ihn gefangen. Als das Haus der Orke komplett
eingesponnen ist, bricht die Spinnenbestie tot zusammen. Der Schemen des
Idmon erscheint und trägt die in das Kind Arachne zurückverwandelte
Spinne zum Hades und folgt ihm in das Totenreich. Zeus lässt daraufhin
einen Regen über der Stadt niedergehen, der alle Bewohner erwachen
lässt.

Asklepios verlässt die Stadt und begegnet auf einer Anhöhe außerhalb der
Stadt Hypaipa einem unerkannten Wanderer. Nach kurzer Unterhaltung
erblickt Asklepios den Hades in der Ferne. Als er sich aufmacht, ihm zu
folgen, erscheint ein kleines Mädchen, flüstert ihm etwas ins Ohr, nimmt
ihn bei der Hand und führt ihn weg von der Straße und vom Hades.

** Historische Ereignisse
-  [[file:untergang-der-stadt-kolophon.org][Untergang der Stadt Kolophon]]
-  [[file:ermordung-des-hades.org][Ermordung des Hades]]
-  [[file:aufstand-der-toten.org][Aufstand der Toten]]
-  [[file:ermordung-der-drei-richter.org][Ermordung der drei Richter]]
-  [[file:tod-des-hermes.org][Tod des Hermes]]
-  [[file:verstuemmelung-der-atropos.org][Verstümmelung der Atropos]]

** Ausführliches Personenverzeichnis
[[file:agdistis.org][Agdistis]] · [[file:aiakos.org][Aiakos]] ·
[[file:aitnaios.org][Aitnaios]] · [[file:alkon.org][Alkon]] · [[file:apollon.org][Apollon]] ·
[[file:arachne.org][Arachne]] · [[file:asklepios.org][Asklepios]] ·
[[file:athene.org][Athene]] · [[file:atropos.org][Atropos]] · [[file:attis.org][Attis]] ·
[[file:autolykos.org][Autolykos]] · [[file:cassandros.org][Cassandros]] ·
[[file:charon.org][Charon]] · [[file:cheiron.org][Cheiron]] · [[file:colydon.org][Colydon]] ·
[[file:damistokles.org][Damistokles]] · [[file:echidna.org][Echidna]] ·
[[file:erebos.org][Erebos]] · [[file:eribotes.org][Eribotes]] ·
[[file:essokles.org][Essokles]] · [[file:eurymedon.org][Eurymedon]] ·
[[file:hades.org][Hades]] · [[file:harpokrates.org][Harpokrates]] · [[file:hera.org][Hera]] ·
[[file:herakles.org][Herakles]] · [[file:hermes.org][Hermes]] ·
[[file:hippolaya.org][Hippolaya]] · [[file:iason.org][Iason]] · [[file:idas.org][Idas]] ·
[[file:idmon.org][Idmon]] · [[file:ikariod.org][Ikariod]] · [[file:ixmos.org][Ixmos]] ·
[[file:kanthos.org][Kanthos]] · [[file:klotho.org][Klotho]] · [[file:klytios.org][Klytios]] ·
[[file:kronos.org][Kronos]] · [[file:kybele.org][Kybele]] · [[file:lachesis.org][Lachesis]] ·
[[file:minos.org][Minos]] · [[file:mopsos.org][Mopsos]] · [[file:okeanos.org][Okeanos]] ·
[[file:onnes.org][Onnes]] · [[file:orke.org][Orke]] · [[file:padmilos.org][Padmilos]] ·
[[file:peleus.org][Peleus]] · [[file:pondros.org][Pondros]] · [[file:poseidon.org][Poseidon]]
· [[file:rhadamanthys.org][Rhadamanthys]] · [[file:sisyphus.org][Sisyphus]] ·
[[file:teiresias.org][Teiresias]] · [[file:thanatos.org][Thanatos]] ·
[[file:thraphes.org][Thraphes]] · [[file:tiphys.org][Tiphys]] · [[file:zeus.org][Zeus]]

*** Orte, Länder, Flüsse
[[file:aipos.org][Aipos]] · [[file:aeolische-strasse.org][Äolische Straße]] ·
[[file:bithynien.org][Bithynien]] · [[file:demeters-tropfen.org][Demeters Tropfen]] ·
[[file:festung-des-hades.org][Festung des Hades]] ·
[[file:hadesfestung.org][Hadesfestung]] · [[file:halle-der-richter.org][Halle der
Richter]] · [[file:herakleia-pontike.org][Herakleia Pontike]] ·
[[file:hexenhain.org][Hexenhain]] · [[file:hypaipa.org][Hypaipa]] ·
[[file:insel-der-moiren.org][Insel der Moiren]] · [[file:kap-tainaron.org][Kap
Tainaron]] · [[file:kokytos.org][Kokytos]] · [[file:kolophon.org][Kolophon]] ·
[[file:lethe.org][Lethe]] · [[file:lydien.org][Lydien]] · [[file:macedonia.org][Macedonia]] ·
[[file:myrina.org][Myrina]] · [[file:orakel-von-klaros.org][Orakel von Klaros]] ·
[[file:orakelhain-olymp.org][Orakelhain (Olymp)]] · [[file:olymp.org][Olymp]] ·
[[file:samothrake.org][Samothrake]] · [[file:sangarios.org][Sangarios]] ·
[[file:zum-kalydonischen-eber.org][Zum Kalydonischen Eber]]

*** Sonstige Begriffe
[[file:aether.org][Aether]] · [[file:agora.org][Agora]] · [[file:armageddon.org][Armageddon]]
· [[file:augentrost.org][Augentrost]] · [[file:blutschau.org][Blutschau]] ·
[[file:bugspriet.org][Bugspriet]] · [[file:eiche-von-dodona.org][Eiche von Dodona]] ·
[[file:euphrasia.org][Euphrasia]] · [[file:fach-weberei.org][Fach (Weberei)]] ·
[[file:fibel.org][Fibel]] · [[file:hadesbrand.org][Hadesbrand]] ·
[[file:hindinnenblut.org][Hindinnenblut]] · [[file:hoplit.org][Hoplit]] ·
[[file:ketos.org][Ketos]] · [[file:kolophonium.org][Kolophonium]] ·
[[file:krater.org][Krater]] · [[file:kriegergriff.org][Kriegergriff]] ·
[[file:lebensfaden.org][Lebensfaden]] · [[file:leviathan.org][Leviathan]] ·
[[file:moiren.org][Moiren]] · [[file:moirenblut.org][Moirenblut]] ·
[[file:mysterien.org][Mysterien]] · [[file:okeaniden.org][Okeaniden]] ·
[[file:pallas.org][Pallas]] · [[file:runks.org][Runkse]] · [[file:schiff-weberei.org][Schiff
(Weberei)]] · [[file:schuetze-weberei.org][Schütze (Weberei)]] ·
[[file:schwarzer-koenig.org][Schwarzer König]] · [[file:zerberus.org][Zerberus]]

** Easter Eggs
ZWÖLFTER GESANG -- Hypaipa

Haus der Orke

#+BEGIN_EXAMPLE
    Ich sollte es wohl lassen,
    aber den Göttern sei Dank
    ist mein Wille schwach.
    ALTE FRAU
    Der Exorzist. Warner Bros. 1973 und 2000 (neue Version).
#+END_EXAMPLE

EPILOGOS -- Der Aar am Firmamente

Anhöhe außerhalb der Stadt Hypaipa.

#+BEGIN_EXAMPLE
    Und meide er das fette Essen,
    es ist ihm nie sehr gut bekommen.
    WANDERER
    Monty Pythons Der Sinn des Lebens. Universal Pictures 1983.
#+END_EXAMPLE
