#+SETUPFILE: ../../org-templates/level-1.org
#+TITLE: Ikareion-Taurusflucht
#+STARTUP: showall

** Personae
-  Menschen
-  [[file:daedalus.org][Daedalus]]: Legendärer Erfinder.
-  [[file:ikarus.org][Ikarus]]: Sein Sohn.
-  [[file:minos.org][König Minos]]: König von Kreta.
-  [[file:pasiphae.org][Pasiphae]]: Gemahlin des Minos. Von einem dem Poseidon
   als Opfer versprochenen Stiere zur Mutter gemacht.
-  Götter
-  [[file:poseidon.org][Poseidon]]: Gott des Meeres.
-  Sonstige Begriffe
-  [[file:kroniden.org][Kroniden]]: Kinder des Kronos.
   -  [[file:zeus.org][Zeus]]
   -  [[file:hades.org][Hades]]
   -  [[file:poseidon.org][Poseidon]]
   -  [[file:hera.org][Hera]]
   -  [[file:hestia.org][Hestia]]
   -  [[file:demeter.org][Demeter]]

** Zusammenfassung
Pasiphae, die Gattin des Minos, hat eine Missgeburt in die Welt gesetzt.
Sie hat sich in widernatürlicher Vereinigung mit dem Stier des Poseidon
vereinigt und ein Kind zur Welt gebracht. Poseidon verlangt von ihr die
Herausgabe des Kindes. Pasiphae weigert sich, weswegen der Meeresgott
das Kind mit einem Liebesfluch belegt: Der nächste, der es erblickt,
wird alles daran setzen, um es vor jedem Schaden zu bewahren.

Kurz darauf erscheint Daedalus mit ein paar Wachen. Er ist gekommen, um
das Kind zu töten. Er bringt es jedoch nicht übers Herz, und nimmt sich
stattdessen selbst des Kindes an. Daedalus beichtet König Minos, dass er
unfähig war, das Kind zu töten. Stattdessen will er ein riesiges
Labyrinth erbauen, um das Kind darin einzusperren. König Minos willigt
ein.

Als Daedalus König Minos Jahre später durch das Labyrinth führt, lässt
dieser ihn in Ketten legen und im Labyrinth zurück. Eine nach seinem
Sohn Ikarus ausgesandte Wache kehrt mit leeren Händen zurück. Daedalus
schafft es, sich von den Ketten zu befreien und flüchtet mit aus Wachs
gefertigten Flügeln von der Insel Kreta. Bei ihm ist ein Jüngling, der
sich allerdings als der junge Stier herausstellt.

** Gesängekatalog
*** PROLOGOS -- Kronidenfluch und wächsern Schwingen
**** Gemächer der Pasiphae. Nacht. Eine Wiege steht im Raum.
POSEIDON, PASIPHAE, in aufgeregtem Gespräch vertieft.

Poseidon verlangt den Sohn aus der widernatürlichen Vereinigung von
Pasiphae und einem Stier als Opfer. Pasiphae weigert sich. Statt das
Kind mit sich zu nehmen, belegt Poseidon es mit einem Liebesfluch: Wer
es als nächster erblickt, wird alles dafür tun, das Kind vor jeglichem
Schaden zu schützen.

**** Himmel über der Ikarischen See.
DAEDALUS und ein JÜNGLING, beide auf wächsernen Schwingen durch die
Lüfte fliegend.

Daedalus und dem Jüngling ist die Flucht vor König Minos gelungen. Der
Jüngling kommt der Sonne ziemlich nahe.

*** ERSTER GESANG -- Pasiphaes sodomisch Schande
**** Nebensaal zum Thronsaal zu Kreta.
DAEDALUS, KÖNIG MINOS, in geheimer Sitzung.

König Minos verlangt von Daedalus, die Missgeburt der Pasiphae aus der
Welt zu schaffen.

*** ZWEITER GESANG -- Im Banne des Kronidenfluchs
**** Kammer der Pasiphae. Nacht. Schummriges Kerzenlicht. Eine Wiege in der Mitte des Raumes.
PASIPHAE, mit irrem Blick vor einem Spiegel sitzend. Das KIND in weiße
Tücher gewickelt in seiner Wiege.

Daedalus erscheint gemeinsam mit ein paar Wachen. Statt das Kind einfach
fortzuschaffen, nimmt er es an sich.

*** DRITTER GESANG -- Streng geheime Attitüden
**** Nebensaal zum Thronsaal zu Kreta.
DAEDALUS, KÖNIG MINOS in geheimer Sitzung.

Daedalus gesteht König Minos, das Kind der Pasiphae nicht töten zu
können. Stattdessen will er ein riesiges Labyrinth erbauen und es darin
einsperren. König Minos nimmt seinen Vorschlag an.

*** VIERTER GESANG -- Im Labyrinth des Stiers des Minos
**** Jahre später. Nebenraum zur tiefsten Kammer des Labyrinths. Rufen und Schreien ertönt von nebenan. Ein Faden liegt auf dem Boden.
DAEDALUS, das Labyrinth mit KÖNIG MINOS und zwei WACHEN begehend.

König Minos lässt Daedalus in seinem Labyrinth in Ketten legen. Seine
Wachen sollen Daedalus' Sohn Ikarus suchen und ebenfalls ins Labyrinth
werfen.

**** Nebenraum zur tiefsten Kammer des Labyrinths. Kurze Zeit später.
DAEDALUS, in Ketten. KÖNIG MINOS, wartend, mit einer WACHE. Die nach
Ikarus ausgesandte WACHE kehrt zurück.

Die Wache kehrt zurück, ohne Ikarus gefunden zu haben. Sie lassen
Daedalus allein zurück. Daedalus lässt ein Werkzeug aus seinem Ärmel
fallen und befreit sich von den Ketten.

*** EPILOGOS -- Flucht durch sengend Heliosstrahlen
**** Himmel über der Ikarischen See.
DAEDALUS und ein JÜNGLING. Beide auf wächsernen Schwingen fliegend.

Daedalus quälen Gewissensbisse, da er statt des Minotaurus seinen Sohn
Ikarus im Labyrinth zurückgelassen hat.

** Historische Ereignisse
-  [[file:bau-des-labyrinths-des-minotaurus.org][Bau des Labyrinths des
   Minotaurus]]

** Ausführliches Personenverzeichnis
-  [[file:asterios.org][Asterios]]
-  [[file:daedalus.org][Daedalus]]
-  [[file:ikarus.org][Ikarus]]
-  [[file:minos.org][Minos]]
-  [[file:pasiphae.org][Pasiphae]]
-  [[file:poseidon.org][Poseidon]]
-  [[file:rhadamanthys.org][Rhadamanthys]]
-  [[file:sarpedon.org][Sarpedon]]

*** Orte, Länder, Flüsse
-  [[file:ikarische%20see.org][Ikarische See]]
-  [[file:kreta.org][Kreta]]

** Sonstige Begriffe
-  [[file:minotaurus.org][Minotaurus]]
